const LearningList = {
  1: {
    author: 'Codecademy',
    name: 'React Part 1 & 2, JavaScript, Responsive Design, HTML, CSS, Git',
    link: 'https://www.codecademy.com/catalog/subject/all',
    type: 'Course',
  },
  2: {
    author: 'FreeCodeCamp',
    name: 'Basic JavaScript',
    link:
      'https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript',
    type: 'Course',
  },
  3: {
    author: 'Various authors',
    name: 'Hack Design',
    link: 'https://hackdesign.org/',
    type: 'Course',
  },
  4: {
    year: '2017 and earlier'
  },
  5: {
    author: 'Taras Mankovski',
    name: 'Microstates Workshop',
    link: 'https://github.com/taras/microstates-workshop',
    repo: 'https://github.com/andreidobrinski/microstates-workshop',
    type: 'Workshop',
  },
  6: {
    author: 'Stephen Grider',
    name: 'Modern React and Redux',
    link: 'https://www.udemy.com/react-redux/',
    repo: 'https://github.com/andreidobrinski/modern-react-redux-course',
    type: 'Course',
  },
  7: {
    author: 'Wes Bos',
    name: 'CSS Grid',
    link: 'https://cssgrid.io/',
    repo: 'https://github.com/andreidobrinski/css-grid',
    type: 'Course',
  },
  8: {
    author: 'Kent C. Dodds',
    name: 'Advanced React Patterns',
    link: 'https://frontendmasters.com/courses/advanced-react-patterns/',
    repo: 'https://github.com/andreidobrinski/advanced-react-patterns-v2',
    type: 'Workshop',
  },
  9: {
    author: 'Kent C. Dodds',
    name: 'Testing React Applications',
    link: 'https://frontendmasters.com/courses/testing-react/',
    repo: 'https://github.com/andreidobrinski/testing-workshop',
    type: 'Workshop',
  },
  10: {
    author: 'Monarch Haveri',
    name: 'React 101',
    link: 'https://github.com/monarchjhaveri/react101',
    repo: 'https://github.com/andreidobrinski/react101',
    type: 'Workshop',
  },
  11: {
    author: 'Designlab',
    name: 'Figma 101',
    link: 'https://trydesignlab.com/figma-101-course/',
    type: 'Course',
  },
  12: {
    author: 'RegexOne',
    name: 'Learn Regular Expressions',
    link: 'https://regexone.com/',
    type: 'Lessons',
  },
  13: {
    author: 'Wes Bos',
    name: 'Mastering Markdown',
    link: 'https://masteringmarkdown.com',
    type: 'Mini Course',
  },
  14: {
    author: 'Matt Gaunt (Google CodeLabs)',
    name: 'Adding Push Notifications to a Web App',
    link:
      'https://developers.google.com/web/fundamentals/codelabs/push-notifications/',
    repo: 'https://github.com/andreidobrinski/web-push-codelab',
    type: 'Tutorial',
  },
  15: {
    author: 'Stephen Grider',
    name: 'The Coding Interview Bootcamp',
    link:
      'https://www.udemy.com/coding-interview-bootcamp-algorithms-and-data-structure/',
    repo: 'https://github.com/andreidobrinski/AlgoCasts',
    type: 'Course',
  },
  16: {
    author: 'Taylor Bell',
    name: 'Build a Blog with React and Markdown using Gatsby',
    link:
      'https://egghead.io/courses/build-a-blog-with-react-and-markdown-using-gatsby',
    repo: 'https://github.com/andreidobrinski/blog-tutorial-gatsby',
    type: 'Egghead Course',
  },
  17: {
    author: 'Zach Goldstein',
    name: 'Penrose Triangle with Three.js',
    link: 'https://github.com/zachgoldstein/penroseTriangle',
    type: 'Workshop',
  },
  18: {
    author: 'Peter Cottle',
    name: 'Learn Git Branching',
    link: 'https://learngitbranching.js.org/',
    type: 'Mini-Course',
  },
  19: {
    author: 'Codecademy',
    name: 'Learn Color Design',
    link: 'https://www.codecademy.com/learn/learn-color-design',
    type: 'Course',
  },
  20: {
    author: 'Nik Graf',
    name: 'GraphQL Data in React with Apollo Client',
    link: 'https://egghead.io/courses/graphql-data-in-react-with-apollo-client',
    repo:
      'https://github.com/andreidobrinski/graphql-apollo-client-course-egghead',
    type: 'Egghead Course',
  },
  21: {
    author: 'Chris Achard',
    name: 'Progressive Web Apps in React with create-react-app',
    link:
      'https://egghead.io/courses/progressive-web-apps-in-react-with-create-react-app',
    repo: 'https://github.com/andreidobrinski/todo-pwa-course',
    type: 'Egghead Course',
  },
  22: {
    year: '2018'
  },
  23: {
    author: 'David Katz',
    name: 'Essentials in JavaScript ES6',
    link: 'https://www.udemy.com/essentials-in-javascript-es6/',
    repo: 'https://github.com/andreidobrinski/es6-course-udemy',
    type: 'Course',
  },
  24: {
    author: 'Marius Schulz',
    name: 'JavaScript Promises in Depth',
    link: 'https://egghead.io/courses/javascript-promises-in-depth',
    type: 'Egghead Course',
  },
  25: {
    author: 'Trevor Miller',
    name: 'Practical Git for Everyday Professional Use',
    link:
      'https://egghead.io/courses/practical-git-for-everyday-professional-use',
    type: 'Egghead Course',
  },
  26: {
    author: 'Stephen Grider',
    name: 'Electron for Desktop Apps: The Complete Developers Guide',
    link: 'https://www.udemy.com/electron-react-tutorial/',
    repo: 'https://github.com/andreidobrinski/electron-course-udemy',
    type: 'Course',
  },
  27: {
    author: 'Codecademy',
    name: 'Learn Express',
    link: 'https://www.codecademy.com/learn/learn-express',
    type: 'Course',
  },
  28: {
    author: 'Ryerson University',
    name: 'Introduction to Web Accessibility',
    link: 'https://de.ryerson.ca/wa/introduction/',
    type: 'Course',
  },
  29: {
    author: 'Kent C. Dodds',
    name: 'React Hooks and Suspense',
    link:
      'https://egghead.io/playlists/react-hooks-and-suspense-650307f2?__s=ns3juptwu4vybog9objt',
    type: 'Egghead Course',
  },
  30: {
    author: 'Stephen Grider',
    name: 'The Complete React Native and Redux Course',
    link: 'https://www.udemy.com/the-complete-react-native-and-redux-course/',
    repo: 'https://github.com/andreidobrinski/react-native-course-udemy',
    type: 'Course',
  },
  31: {
    author: 'Cameron Nokes',
    name: 'Advanced Bash Automation for Web Developers',
    link: 'https://www.udemy.com/the-complete-react-native-and-redux-course/',
    type: 'Egghead Course',
  },
  32: {
    name: 'Simplify React Apps with React Hooks',
    author: 'Kent C. Dodds',
    link: 'https://egghead.io/courses/simplify-react-apps-with-react-hooks',
    type: 'Egghead Course',
  },
  33: {
    name: 'Typescript with modern React (i.e. hooks, context, suspense)',
    author: 'Richard Oliver Bray',
    link: 'https://www.udemy.com/typescript-with-react-hooks-and-context/',
    repo: 'https://github.com/andreidobrinski/typescript-with-react-course-udemy',
    type: 'Course',
  },
  34: {
    name: 'JavaScript ES2019 in Practice',
    author: 'Mike Sherov',
    link: 'https://egghead.io/lessons/javascript-course-overview-javascript-es2019-in-practice',
    type: 'Egghead Course',
  },
  35: {
    name: 'Building Neural Networks in JavaScript',
    author: 'Matthew Mihok',
    link: 'https://github.com/mihok/workshop-aug13',
    repo: 'https://github.com/andreidobrinski/workshop-aug13',
    type: 'Workshop',
  },
  36: {
    name: 'Augmented Reality Workshop',
    author: 'Simon Stern',
    link: 'https://github.com/simistern/ARWorkshop01',
    repo: 'https://github.com/andreidobrinski/react-ar-workshop-sept-2019',
    type: 'Workshop',
  },
  37: {
    name: `Dart and Flutter: The Complete Developer's Guide`,
    author: 'Stephen Grider',
    link: 'https://www.udemy.com/course/dart-and-flutter-the-complete-developers-guide/',
    repo: 'https://github.com/andreidobrinski/dart-and-flutter-course-udemy',
    type: 'Course',
  },
  38: {
    year: '2019'
  },
  39: {
    name: `Typescript: The Complete Developer's Guide [2020]`,
    author: 'Stephen Grider',
    link: 'https://www.udemy.com/course/typescript-the-complete-developers-guide/',
    repo: 'https://github.com/andreidobrinski/typescript-course-udemy',
    type: 'Course',
  },
  40: {
    name: 'React: Using TypeScript',
    author: 'Emmanuel Henri',
    link: 'https://www.linkedin.com/learning/react-using-typescript',
    repo: 'https://github.com/andreidobrinski/react-using-typescript-li-learning',
    type: 'Course',
  },
  41: {
    name: 'Testing React Applications with Jest',
    author: 'Daniel Stern',
    type: 'Course',
    link: 'https://app.pluralsight.com/library/courses/testing-react-applications-jest',
    repo: 'https://github.com/andreidobrinski/testing-react-applications-with-jest-ps',
  },
  42: {
    name: 'Payment Card Security, Processing, and the PCI Standards',
    author: 'John Elliott',
    type: 'Course',
    link: 'https://www.pluralsight.com/courses/payment-card-security-processing-pci-standards',
    repo: 'https://github.com/andreidobrinski/pluralsight-security-courses/blob/master/payment-card-security-processing-and-the-PCI-standards.md',
  },
  43: {
    name: 'Defending Against JavaScript Keylogger Attacks on Payment Card Information',
    author: 'John Elliott and Troy Hunt',
    type: 'Course',
    link: 'https://www.pluralsight.com/courses/defending-javascript-keylogger-attacks-pci',
    repo: 'https://github.com/andreidobrinski/pluralsight-security-courses/blob/master/defending-against-JS-keylogger-ps-course.md',
  },
  44: {
    name: 'Play by Play: OWASP Top 10 2017',
    author: 'Andrew van der Stock and Troy Hunt',
    type: 'Course',
    link: 'https://www.pluralsight.com/courses/play-by-play-owasp-top-ten-2017',
    repo: 'https://github.com/andreidobrinski/pluralsight-security-courses/blob/master/owasp-top-10-2017.md',
  },
  45: {
    name: 'Play by Play: JavaScript Security',
    author: 'Troy Hunt and Aaron Powell',
    type: 'Course',
    link: 'https://www.pluralsight.com/courses/play-by-play-javascript-security',
    repo: 'https://github.com/andreidobrinski/pluralsight-security-courses/blob/master/js-security.md',
  },
  46: {
    name: 'Play by Play: What You Need to Know About HTTPS Today',
    author: 'Troy Hunt and Lars Klint',
    type: 'Course',
    link: 'https://www.pluralsight.com/courses/play-by-play-https-what-you-need-know-about-today',
    repo: 'https://github.com/andreidobrinski/pluralsight-security-courses/blob/master/what-you-need-to-know-about-https-today.md',
  },
  47: {
    name: 'JSP Tutorial',
    author: 'TutorialsPoint',
    type: 'Tutorial',
    link: 'https://www.tutorialspoint.com/jsp/index.htm',
  },
  48: {
    name: 'Docker and Kubernetes: The Complete Guide',
    author: 'Stephen Grider',
    type: 'Course',
    link: 'https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/',
    repo: 'https://github.com/andreidobrinski/docker-kubernetes-course-udemy',
  },
  49: {
    name: 'Node with React: Fullstack Web Development',
    author: 'Stephen Grider',
    type: 'Course',
    link: 'https://www.udemy.com/course/node-with-react-fullstack-web-development',
    repo: 'https://github.com/andreidobrinski/node-with-react-fullstack-course-udemy',
  },
  50: {
    name: 'React Testing Masterclass',
    author: 'Kati Frantz',
    type: 'Course',
    link: 'https://katifrantz.com/course/react-testing-masterclass',
    repo: 'https://github.com/andreidobrinski/react-testing-masterclass-course',
  },
  // 51: {
  //   name: 'Microservices with Node JS and React',
  //   author: 'Stephen Grider',
  //   type: 'Course',
  //   link: 'https://www.udemy.com/course/microservices-with-node-js-and-react/',
  //   repo: 'https://github.com/andreidobrinski/microservices-course-udemy',
  //   inProgress: true,
  // },
  99: { year: '2020' }
};

export default LearningList;
